MergerFS and Rclone Fixes

diff --git a/root/etc/services.d/rclone-mount/run b/root/etc/services.d/rclone-mount/run
--- a/root/etc/services.d/rclone-mount/run
+++ b/root/etc/services.d/rclone-mount/run
@@ -1,14 +1,31 @@
 #!/usr/bin/with-contenv sh
 
-if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
-  echo "Error: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
-  exit 1
-fi
+uid=${PUID:-1000}
+user=$(getent passwd $uid | awk -F: '{print $1}')
 
 rclone_conf_path=$(grep -P "rclone_config_path" ${CLOUDPLOW_CONFIG} | awk -F: '{print $2}' | awk -F\" '{print $2}')
 
-mount_command="rclone mount --config=$rclone_conf_path --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /cloud"
+if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
+  echo "ERROR: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
+  exit 1
+  else
+  echo "INFO: Creating mountcheck file incase it's not present."
+  touch mount.check
+  rclone copy mount.check $RCLONE_REMOTE_MOUNT -vv --no-traverse
+fi
 
-echo "Executing => $mount_command"
+if [ -z "$RCLONE_LANDING_MOUNT" ]; then
+  echo "INFO: RCLONE_LANDING_MOUNT environment variable was not passed to the container. Will Not Utilize within script."
+  landing_mount_command=""
+  else
+  echo "INFO: RCLONE_LANDING_MOUNT environment variable set. Will Mount in additions to the RCLONE_REMOTE_MOUNT"
+  landing_mount_command="rclone mount --config=${rclone_conf_path} $RCLONE_MOUNT_OPTIONS $RCLONE_LANDING_MOUNT $LANDING_LOCATION"
+fi
+
+mount_command="rclone mount --config=${rclone_conf_path} $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT $CLOUD_LOCATION"
+
+echo "EXECUTING => $mount_command"
 exec \
-	s6-setuidgid abc $mount_command
+	s6-setuidgid $user $mount_command &
+	s6-setuidgid $user $landing_mount_command
+
